void set_jb_exit(void);
void jb_play_badgio(void);
void jb_play_blurgggh(void);
void jb_play_boss(void);
void jb_play_burgundy_power(void);
void jb_play_dirigible(void);
void jb_play_gameof(void);
void jb_play_imperial(void);
void jb_play_j46k(void);
void jb_play_mau5(void);
void jb_play_nge(void);
void jb_play_slurm(void);
void jb_switch_pages(void);
void jukebox_task(void *args);
