#!/bin/tcsh -f

ls -lt ../harmony_badge_2018.X/dist/pic32mx_usb_badge_int_dyn/production/harmony_badge_2018.X.production.hex

./pic32usb ../harmony_badge_2018.X/dist/pic32mx_usb_badge_int_dyn/production/harmony_badge_2018.X.production.hex
